{
 "title": "Guard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Guard HTTP Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"guard\",code=\"500\"}[1m])",
     "legendFormat": "500"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"guard\",code=\"200\"}[1m])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"guard\",code=\"503\"}[1m])",
     "legendFormat": "503"
    }
   ]
  },
  {
   "title": "Token Reviews",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tokenreviews_hendler_requests_total{service=\"guard\"}[1m])",
     "legendFormat": "Totalt requests"
    },
    {
     "expr": "rate(tokenreviews_handler_requests_in_flight{service=\"guard\"}[1m])",
     "legendFormat": "Requests in flight"
    }
   ]
  },
  { "title": "Guard Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{service=\"guard\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{service=\"guard\"}[1m])",
     "legendFormat": "Virtual"
    },
    {
     "expr": "rate(process_resident_memory_bytes{service=\"guard\"}[1m])",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{service=\"guard\"}",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}