version: 2
run:
  timeout: 10m
  modules-download-mode: vendor
  exclude-files:
    - "generated.*\\.go$"
  exclude-dirs:
    - client
    - vendor
    - third_party
    - testdata
    - examples
    - Godeps
    - builtin

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - govet
    - ineffassign
    - unparam
    - unused
