apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN1RENDQWFDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFOTVFzd0NRWURWUVFERXdKallUQWUKRncweE56QTRNamt4TkRJek16aGFGdzB5TnpBNE1qY3hOREl6TXpoYU1BMHhDekFKQmdOVkJBTVRBbU5oTUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBclF3aGRweVE3KzBaVzBDMFpEblI1VS85CjdaVmgyODRtYjdYSmVVaHM0QmI0UHE2Mk1remZpc2lzdXZQZmJzK2Y3dW1oeXhyOGVLak10RlJyc3ZQakhUeDUKTG5rM0hvdE1wNGtCbGJjOTl4dExqN0VwazlXSVNNUW42OEo4K0NCU2N3aFZ1Zlg4NndrNFo3cTZuYXdEUTlRbApyMG1qNWZCVFZ1K3gzYWhXa1F4Rzczd3QxRUdZRkRFMFR1UlV6OXpDclk2bFZzdnZJcXlHL04wWHlUVHNMeFQxCmtOOHRnU3cwVWJOakhGMFVmejhpN05wK1RBZkRFT1pUMWx3SllkSlJ2RjMvYTBRRmdHWTg3K1BJQmhvQklZd1YKU2RXZkRjVWVjcUVuWXkxMEF5MDhZeEZxUTlSNTM4djlpUUxYenZqSVdsYWdDSXBCejB2UDB3dFp4a0lGaFFJRApBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFsanRtbzJwMklvVmhKTXZ4MEFNM08xUkxHMGVRbHY5QTNQWm14dTlWemJkaWZjUFYKTWFaeHp3blVtcjRFa2Y2RmY4WGI4Sk90ZWJUdWo4eDA4UWVaSFRnY3JJYitXdk9jVHJLTkFyeE1Ud0JHcnRRTwp0eWhxanJUSXE5SS9kZUNNeCt4RkNPSFVzdmNEa1FmRVVoZ21YWW5TVEdOU3poNmFmdlU5STFUVUNlWXRFeHlDCm5aaDlPd3hzcGFmcFhBRWdmdStTL0F6WFpLV255bjgyVHpGVTZnaFpFZnVDcndMd2JQRmlaS25ESm1mYlNWM1YKVGljTWdsSkNmZldsdk96OUN3eGtxQlRHNDZvUGZraFZVNElKS3pwekVXQXU2Q3lua09RalkvN2VDd1VFc1NWMQpwM0hZTXpNa05aRzlDNldSakd4VlF4NUo4djRuR1UzcXo2UTk4dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyRENDQWNDZ0F3SUJBZ0lJZG82TThwTStIbFV3RFFZSktvWklodmNOQVFFTEJRQXdEVEVMTUFrR0ExVUUKQXhNQ1kyRXdIaGNOTVRjd09ESTVNVFF5TXpNNFdoY05NVGd3T0RJNU1UUXlNelV4V2pBUk1ROHdEUVlEVlFRRApFd1p6WlhKMlpYSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEYUFoeWdZRU8zCmxOczVpdnkyelJuZDFYSkZIdXhEa2FhRXd6YWcyVEk3UkJwdDNkNzgxYVR4MG1Jd2pOczMybVlWVnEvbnNwUmYKV2JyeEhtVGFpRVl1VGwwU1VHREhadFY0VHp3b3d1Ni9DQzg0NWk2Uk05L292OGJKaUR3UmxYZFE0bVRiN1pKSwpQdmdxUllDSkwwZVF1RDBCQldVa28zcDY2SjArZWNFUVZPaXRobnNDbi9DSkt5c043dVMrNGUvRklzWDhNM2VrCll4SlVLTGFTYlc4YnZmOXk2U1lBNXhTSHhEM2VnV1VJZSt0S0NYUCtPTUY4WUUxeGlLdGJIcmpiNkFoaWtmRGwKdUxzM1Q5Rm9WUHIxTEE0ZStuNmhScUttTjROOEppZnZJOGVDeDhkWFZNajM4dUN0SEFNR3NOSm90TitTUGdpcwpKNHorZDI5RTNJMkpBZ01CQUFHak9EQTJNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyCkJnRUZCUWNEQVRBUEJnTlZIUkVFQ0RBR2h3UUtZQXBnTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDREJsMy8Ka1kzU2ZmWkl5MkwvOXgzK2lLcmhKSytDYlJVTUhIN3VQdW5tVFpQc0hxVlN0Mmp2c1d4ZUVxMnJGMWlTM291Zgo5ZkxpbTdMMW1jNzhoS3V1WHIyWjZsNWk4L0RKR1djaUdjNThaTzkzQnJseXMrMWYwV1ZPWUdCdWNva0pHTWJWCjkvL1QzNldzV0R0ck1Gei94V1E1MEsvbU8wK3UwUGRiMkU1Qy9kc2ZYaHRCWCtnaGZHMm51SDhYNWFFSDNpTmwKeXREajdhQ1Q1ZU5jeTlrQUtHMGxRYWtEc1FobW1ZMjkxMldzTkh6RWFIek5maU9ZKy90TTNTOGwvTjFDT1lwYgo4WW5ZTHB1TWN5dXNZU0cxL0ppTmd3VzBwQ3ZlcVZuRThhbWhLOC9mYWR4V0ZvQUVwYXl0WnE0ZDVZcTdXVzlGClE5QWFFQ2hwcXNvSG5WU2wKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcGdJQkFBS0NBUUVBMmdJY29HQkR0NVRiT1lyOHRzMFozZFZ5UlI3c1E1R21oTU0yb05reU8wUWFiZDNlCi9OV2s4ZEppTUl6Yk45cG1GVmF2NTdLVVgxbTY4UjVrMm9oR0xrNWRFbEJneDJiVmVFODhLTUx1dndndk9PWXUKa1RQZjZML0d5WWc4RVpWM1VPSmsyKzJTU2o3NEtrV0FpUzlIa0xnOUFRVmxKS042ZXVpZFBubkJFRlRvcllaNwpBcC93aVNzckRlN2t2dUh2eFNMRi9ETjNwR01TVkNpMmttMXZHNzMvY3VrbUFPY1VoOFE5M29GbENIdnJTZ2x6Ci9qakJmR0JOY1lpcld4NjQyK2dJWXBIdzViaTdOMC9SYUZUNjlTd09IdnArb1VhaXBqZURmQ1luN3lQSGdzZkgKVjFUSTkvTGdyUndEQnJEU2FMVGZrajRJckNlTS9uZHZSTnlOaVFJREFRQUJBb0lCQVFDTE9VQUkxNUZIWXlQaAppclk3RTU2S1FhNjVIN2RvcTFKNWhLV1ZjVCtZQTdVUkp0a3FCRkpUTUxVT0psWTFSQjlmVHo0RkxORitWektBCm01Vnl6Z1pydWhYTUJWTFk1UDQ4MS9VbVh0N1RWcW01bjU1cmtvSlRCRzR4OC9QUWt2Qmcwa1B4QTdZaC9qYkQKNENEbSt5K3I1MHptSXdqbHJoVWcrdjY0a0U3UVd3dUJDTjlHSEs3bTdNamZGT2cwUXJFR3lOMkhLd3dYUmdSSgpMNS8zNXo3NnhhdUR3N04vdkdyNUVSMDVUSjF0eis3K3IxazBsUHRtd0hwamtOYmxlQU1TWGVncGJqdXovemRGCm94N1hpUG1FSUxIRGg2cEVCRnV5WURkL1YxZk1tZGhXQXBodTV1VUtWTjJURWxWeXUvRHNoanR1Y1FWc1pFLzEKdjl6RmFxUDFBb0dCQU9wVldMa3hCTzlVK2FRTFZsR1FoYUZPQnpLWEpVaE1xaTh4S2hlMnlIQ1gyUTZGMG9qRQpDeEM0Z3VLZEZhRnl3ZVJ1LzRQNEN1NWtZT0VzRWdOc3JLSHlOQ3VWSUkwNzI2WEVGN0VOUmFwY3g0NWk3ZFpkCjhsWHM4dklzTnJYZmJyR2Q4TmNWSEhjeXY2b1J4MElqS2p3elhIZU5Mc0MzZW5GWkFJU0xLaW5UQW9HQkFPNHEKV2J2aExjRlVoQWVySXFzd0dyMkwrT1lKVzNSM0JUdFg5eDdldTJzbGtNWTVJUkRoNnVxME0yb3p2Uzh4UWk4Nwo0MEFmUG01dkNFRW5veWhxY3ZGSmZ0bzRIdlhucjE5WW55VnBBRE5GZmd5Qi8vWGF4NTVicStRSzUySUpQUFlLCkQxQWNEbVZ5T09KT3VneE9mY00wcU1rVEdEbDA4QklsbGJxNFlSV3pBb0dCQUlGWnV5Lytyd3F0alYvUUlrWEQKMFAvSllvKzZmd241eDdkbEhDY2E3bW00YUVocjlsc29YRE5PcG5FUTVPL0p1TjJ2cDd2aEg2ZVlJU0lxZ1ljQwpaZ2krK2ExVkZETGg1ODBKQVVycVdKcEJ2S1lNVmQwTzNzWXZsYXU0WERyb3F1SEFuVUVjbGluMkNYYUhlY1k0ClF3Z1lFZUtzUERLRkZVR2NMM3o2bEx1aEFvR0JBSUdLSzNDVFU4MjU2RzQ3V1FuL2lpdmF2REJ5bW5uSVd1SWkKUUZsY0VGaUJBRE93MHhsWnArcXN4T0pZN2VlRFJWcG5tbjFBQVRjVDBVdVBBYUZ6OUx6a21zaWFpY3g2amRxdwpXeTkvNHdvQUhFVTFXRUVqRkR3LzVFaU8zYmRuQ3U5UUhYQVhNb1ZmRVMyV1lIOWRHZTVZOEEwZUE2a012NTgvCkxpZDNMZWNkQW9HQkFLSUVZN0xieU1OU3UxdjNkN1lJZEYzaWR6TjlkL3M5M1BoNHNlSk05NVZJUG1WTEZ5ZW4KOE1hcStzYWdKR2pDTkRsZ0U3ZXV0S0JmRFkzRVk4TnVvVjRONkpSM1FsWWU4SDhHLzM5RFBEUzdZNzU0d0kySgp2cjVCanJRM1Vxem5HSE9oNXcwQlZoV3JUaVdXRTZjV3B6dUFuTmh6RHFPQ1Z5aU54cysrMVI5TAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: guard
  name: guard-pki
  namespace: kube-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: guard
  name: guard
  namespace: kube-system
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guard
    spec:
      containers:
      - args:
        - run
        - --v=3
        - --ca-cert-file=/srv/guard/pki/ca.crt
        - --cert-file=/srv/guard/pki/tls.crt
        - --key-file=/srv/guard/pki/tls.key
        image: appscode/guard:canary
        name: guard
        ports:
        - containerPort: 9844
          name: web
          protocol: TCP
        - containerPort: 56790
          name: ops
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /srv/guard/pki
          name: guard-pki
      volumes:
      - name: guard-pki
        secret:
          defaultMode: 365
          secretName: guard-pki
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: guard
  name: guard
  namespace: kube-system
spec:
  clusterIP: 10.96.10.96
  ports:
  - name: web
    port: 9844
    protocol: TCP
    targetPort: web
  selector:
    app: guard
  type: ClusterIP
status:
  loadBalancer: {}

